# Generated by Django 2.2.5 on 2020-03-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', '이메일'), ('github', '깃허브'), ('kakao', '카카오'), ('naver', '네이버')], default='email', max_length=50),
        ),
    ]
