# Generated by Django 2.2.5 on 2020-01-23 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, verbose_name='숙소명')),
                ('description', models.TextField(verbose_name='설명')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='국가')),
                ('city', models.CharField(max_length=80, verbose_name='도시')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('address', models.CharField(max_length=140, verbose_name='주소')),
                ('guests', models.IntegerField(verbose_name='게스트')),
                ('beds', models.IntegerField(verbose_name='침대')),
                ('bedrooms', models.IntegerField(verbose_name='침실')),
                ('baths', models.IntegerField(verbose_name='욕실')),
                ('check_in', models.TimeField(verbose_name='체크인')),
                ('check_out', models.TimeField(verbose_name='체크아웃')),
                ('instant_book', models.BooleanField(default=False, verbose_name='즉시 예약')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='호스트')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
