# Generated by Django 2.2.5 on 2020-01-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200123_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': '사진', 'verbose_name_plural': '사진'},
        ),
    ]
