# Generated by Django 2.2.5 on 2020-01-23 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0005_auto_20200123_1341'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('confirmed', '수락됨'), ('canceled', '취소됨')], default='pending', max_length=12, verbose_name='예약 상태')),
                ('check_in', models.DateField(verbose_name='체크인')),
                ('check_out', models.DateField(verbose_name='체크아웃')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='게스트')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room', verbose_name='숙소')),
            ],
            options={
                'verbose_name': '예약',
                'verbose_name_plural': '예약',
                'ordering': ['created'],
            },
        ),
    ]
