# Generated by Django 2.2.5 on 2020-03-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_bookedday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedday',
            name='day',
            field=models.DateField(verbose_name='예약 날짜'),
        ),
        migrations.AlterField(
            model_name='bookedday',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Reservation', verbose_name='예약'),
        ),
    ]
