# Generated by Django 2.2.5 on 2020-01-23 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0005_auto_20200123_1341'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('review', models.TextField(verbose_name='후기')),
                ('accuracy', models.IntegerField(verbose_name='정확성')),
                ('communication', models.IntegerField(verbose_name='의사소통')),
                ('cleanliness', models.IntegerField(verbose_name='청결도')),
                ('location', models.IntegerField(verbose_name='위치')),
                ('check_in', models.IntegerField(verbose_name='체크인')),
                ('value', models.IntegerField(verbose_name='가치')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room', verbose_name='숙소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
