# Generated by Django 2.2.5 on 2020-01-23 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '후기', 'verbose_name_plural': '후기'},
        ),
    ]
