# Generated by Django 2.2.5 on 2020-01-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['created'], 'verbose_name': '목록', 'verbose_name_plural': '목록'},
        ),
    ]
